### LOCAL DB
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${FESTIE_LOCAL_DB_URL}
    username: ${FESTIE_LOCAL_DB_USERNAME}
    password: ${FESTIE_LOCAL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
    com.umc.FestieBE: debug

#Open API
openapi:
  FIXED_API_KEY : e7280f000b59428793167d4b36222d7b

logging:
  level:
    root=DEBUG:
---

### PROD DB
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${FESTIE_PROD_DB_URL}
    username: ${FESTIE_PROD_DB_USERNAME}
    password: ${FESTIE_PROD_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

logging.level:
    com.umc.FestieBE: debug
    org.hibernate.SQL: debug