### LOCAL DB
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: ${FESTIE_LOCAL_DB_URL}
    #username: ${FESTIE_LOCAL_DB_USERNAME}
#    password: ${FESTIE_LOCAL_DB_PASSWORD}

    url: jdbc:mysql://127.0.0.1:3306/festie
    username: root
    password: Rlarmstlr99!

  security:

    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      token-validity-in-seconds: 86400


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
    com.umc.FestieBE: debug


---

### PROD DB
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${FESTIE_PROD_DB_URL}
    username: ${FESTIE_PROD_DB_USERNAME}
    password: ${FESTIE_PROD_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

logging.level:
    com.umc.FestieBE: debug
    org.hibernate.SQL: debug