## AWS S3 (이미지 업로드)
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${S3_BUCKET_ACCESS_KEY}
      secret-key: ${S3_BUCKET_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


logging.level:
  com.amazonaws.util.EC2MetadataUtils: error


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/festie
    username: root
    password: Rlarmstlr99!

  security:
    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      token-validity-in-seconds: 86400

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true # hibernate 로그 남길지


openapi:
  FIXED_API_KEY: e7280f000b59428793167d4b36222d7b

logging:
  level:
    org.hibernate.SQL: debug
